import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        {
          type: 'category',
          label: 'Component Diagrams',
          items: [
            'architecture/components/aerospike-py',
            'architecture/components/acko',
            'architecture/components/cluster-manager',
            'architecture/components/plugins',
          ],
        },
        'architecture/deployment-topology',
        'architecture/interactive-diagrams',
        {
          type: 'category',
          label: 'Architecture Decision Records',
          link: {type: 'doc', id: 'architecture/adr-index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'architecture/adr',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Roadmap',
      items: [
        'roadmap/current',
        {
          type: 'category',
          label: 'Milestones',
          items: ['roadmap/milestones/Q1'],
        },
      ],
    },
    {
      type: 'category',
      label: 'History',
      items: [
        {
          type: 'category',
          label: 'Changelog',
          items: [
            'history/changelog/aerospike-py',
            'history/changelog/acko',
            'history/changelog/cluster-manager',
            'history/changelog/plugins',
          ],
        },
        {
          type: 'category',
          label: 'Decisions',
          items: ['history/decisions/2026-03'],
        },
        {
          type: 'category',
          label: 'Releases',
          items: ['history/releases/release-matrix'],
        },
        {
          type: 'category',
          label: 'PR History',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'aerospike-py',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'history/pr-history/aerospike-py',
                },
              ],
            },
            {
              type: 'category',
              label: 'ACKO',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'history/pr-history/acko',
                },
              ],
            },
            {
              type: 'category',
              label: 'Cluster Manager',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'history/pr-history/cluster-manager',
                },
              ],
            },
            {
              type: 'category',
              label: 'Plugins',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'history/pr-history/plugins',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Coordination',
      items: [
        'coordination/labels',
        'coordination/agentic-workflow',
        'coordination/review-process',
      ],
    },
    {
      type: 'category',
      label: 'Goals',
      items: [
        'goals/project-goals',
        'goals/project-design',
        'goals/project-timeline',
      ],
    },
  ],
};

export default sidebars;
